// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"git.corp.zgcszkw.com/authhub/backend"
	"git.corp.zgcszkw.com/authhub/config"
	"git.corp.zgcszkw.com/authhub/server"
	"git.corp.zgcszkw.com/authhub/service"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/golang-migrate/migrate/v4/source/github"
	_ "github.com/jackc/pgx/v5"
)

// Injectors from wire.go:

func initApp(ctx context.Context, cfg *config.Config) (*server.Server, error) {
	recognizeRepo, err := backend.NewOpenocrClient(cfg)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(recognizeRepo)
	serverServer, err := server.NewServer(cfg, serviceService)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
