// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: rpc_sirius.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XMin int32  `protobuf:"varint,2,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	YMin int32  `protobuf:"varint,3,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	XMax int32  `protobuf:"varint,4,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMax int32  `protobuf:"varint,5,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
}

func (x *TextBox) Reset() {
	*x = TextBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBox) ProtoMessage() {}

func (x *TextBox) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBox.ProtoReflect.Descriptor instead.
func (*TextBox) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{0}
}

func (x *TextBox) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextBox) GetXMin() int32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *TextBox) GetYMin() int32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *TextBox) GetXMax() int32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *TextBox) GetYMax() int32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

type LineInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text     string     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TextBoxs []*TextBox `protobuf:"bytes,6,rep,name=text_boxs,json=textBoxs,proto3" json:"text_boxs,omitempty"`
}

func (x *LineInfo) Reset() {
	*x = LineInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineInfo) ProtoMessage() {}

func (x *LineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineInfo.ProtoReflect.Descriptor instead.
func (*LineInfo) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{1}
}

func (x *LineInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LineInfo) GetTextBoxs() []*TextBox {
	if x != nil {
		return x.TextBoxs
	}
	return nil
}

type RecognizeTextAutoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecognizeTextAutoRequest) Reset() {
	*x = RecognizeTextAutoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeTextAutoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeTextAutoRequest) ProtoMessage() {}

func (x *RecognizeTextAutoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeTextAutoRequest.ProtoReflect.Descriptor instead.
func (*RecognizeTextAutoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeTextAutoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecognizeTextAutoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonText    *Text       `protobuf:"bytes,1,opt,name=json_text,json=jsonText,proto3" json:"json_text,omitempty"`
	ExcelFileId string      `protobuf:"bytes,2,opt,name=excel_file_id,json=excelFileId,proto3" json:"excel_file_id,omitempty"`
	LineInfos   []*LineInfo `protobuf:"bytes,3,rep,name=line_infos,json=lineInfos,proto3" json:"line_infos,omitempty"`
	Angle       float32     `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Scale       float32     `protobuf:"fixed32,5,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *RecognizeTextAutoResponse) Reset() {
	*x = RecognizeTextAutoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeTextAutoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeTextAutoResponse) ProtoMessage() {}

func (x *RecognizeTextAutoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeTextAutoResponse.ProtoReflect.Descriptor instead.
func (*RecognizeTextAutoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{3}
}

func (x *RecognizeTextAutoResponse) GetJsonText() *Text {
	if x != nil {
		return x.JsonText
	}
	return nil
}

func (x *RecognizeTextAutoResponse) GetExcelFileId() string {
	if x != nil {
		return x.ExcelFileId
	}
	return ""
}

func (x *RecognizeTextAutoResponse) GetLineInfos() []*LineInfo {
	if x != nil {
		return x.LineInfos
	}
	return nil
}

func (x *RecognizeTextAutoResponse) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *RecognizeTextAutoResponse) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{4}
}

func (x *Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type OpenOcrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *OpenOcrRequest) Reset() {
	*x = OpenOcrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOcrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOcrRequest) ProtoMessage() {}

func (x *OpenOcrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOcrRequest.ProtoReflect.Descriptor instead.
func (*OpenOcrRequest) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{5}
}

func (x *OpenOcrRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenOcrRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type OpenOcrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxes []*TextBox `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
}

func (x *OpenOcrResponse) Reset() {
	*x = OpenOcrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOcrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOcrResponse) ProtoMessage() {}

func (x *OpenOcrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOcrResponse.ProtoReflect.Descriptor instead.
func (*OpenOcrResponse) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{6}
}

func (x *OpenOcrResponse) GetBoxes() []*TextBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type GenerateImgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Boxes []*TextBox `protobuf:"bytes,2,rep,name=boxes,proto3" json:"boxes,omitempty"`
}

func (x *GenerateImgRequest) Reset() {
	*x = GenerateImgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImgRequest) ProtoMessage() {}

func (x *GenerateImgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImgRequest.ProtoReflect.Descriptor instead.
func (*GenerateImgRequest) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateImgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerateImgRequest) GetBoxes() []*TextBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type GenerateImgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenerateImgResponse) Reset() {
	*x = GenerateImgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sirius_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImgResponse) ProtoMessage() {}

func (x *GenerateImgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sirius_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImgResponse.ProtoReflect.Descriptor instead.
func (*GenerateImgResponse) Descriptor() ([]byte, []int) {
	return file_rpc_sirius_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateImgResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rpc_sirius_proto protoreflect.FileDescriptor

var file_rpc_sirius_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x71, 0x0a, 0x07, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f,
	0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x78, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x78, 0x4d, 0x69, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x79, 0x5f,
	0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x4d, 0x69, 0x6e, 0x12,
	0x13, 0x0a, 0x05, 0x78, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x78, 0x4d, 0x61, 0x78, 0x12, 0x13, 0x0a, 0x05, 0x79, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x4d, 0x61, 0x78, 0x22, 0x48, 0x0a, 0x08, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x62, 0x6f, 0x78, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x08, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x6f, 0x78, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65,
	0x54, 0x65, 0x78, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xbf, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x63,
	0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x22, 0x20, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x63, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x22, 0x34, 0x0a, 0x0f, 0x4f, 0x70, 0x65,
	0x6e, 0x4f, 0x63, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05,
	0x62, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x05, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x22,
	0x47, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f,
	0x78, 0x52, 0x05, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x70, 0x2e, 0x7a, 0x67, 0x63, 0x73,
	0x7a, 0x6b, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x68, 0x75, 0x62, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_sirius_proto_rawDescOnce sync.Once
	file_rpc_sirius_proto_rawDescData = file_rpc_sirius_proto_rawDesc
)

func file_rpc_sirius_proto_rawDescGZIP() []byte {
	file_rpc_sirius_proto_rawDescOnce.Do(func() {
		file_rpc_sirius_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_sirius_proto_rawDescData)
	})
	return file_rpc_sirius_proto_rawDescData
}

var file_rpc_sirius_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_sirius_proto_goTypes = []interface{}{
	(*TextBox)(nil),                   // 0: pb.TextBox
	(*LineInfo)(nil),                  // 1: pb.LineInfo
	(*RecognizeTextAutoRequest)(nil),  // 2: pb.RecognizeTextAutoRequest
	(*RecognizeTextAutoResponse)(nil), // 3: pb.RecognizeTextAutoResponse
	(*Text)(nil),                      // 4: pb.Text
	(*OpenOcrRequest)(nil),            // 5: pb.OpenOcrRequest
	(*OpenOcrResponse)(nil),           // 6: pb.OpenOcrResponse
	(*GenerateImgRequest)(nil),        // 7: pb.GenerateImgRequest
	(*GenerateImgResponse)(nil),       // 8: pb.GenerateImgResponse
}
var file_rpc_sirius_proto_depIdxs = []int32{
	0, // 0: pb.LineInfo.text_boxs:type_name -> pb.TextBox
	4, // 1: pb.RecognizeTextAutoResponse.json_text:type_name -> pb.Text
	1, // 2: pb.RecognizeTextAutoResponse.line_infos:type_name -> pb.LineInfo
	0, // 3: pb.OpenOcrResponse.boxes:type_name -> pb.TextBox
	0, // 4: pb.GenerateImgRequest.boxes:type_name -> pb.TextBox
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_sirius_proto_init() }
func file_rpc_sirius_proto_init() {
	if File_rpc_sirius_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_sirius_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeTextAutoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeTextAutoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenOcrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenOcrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sirius_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_sirius_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_sirius_proto_goTypes,
		DependencyIndexes: file_rpc_sirius_proto_depIdxs,
		MessageInfos:      file_rpc_sirius_proto_msgTypes,
	}.Build()
	File_rpc_sirius_proto = out.File
	file_rpc_sirius_proto_rawDesc = nil
	file_rpc_sirius_proto_goTypes = nil
	file_rpc_sirius_proto_depIdxs = nil
}
